[package]
name = "bevy_stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.15"

[dev-dependencies]
bevy_turborand = "0.10"
rand = "0.8"
