[package]
name = "bevy_stats"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14"

[dev-dependencies]
bevy_turborand = "0.9"
rand = "0.8"
